More code :D

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -55,6 +55,130 @@ AM_CONDITIONAL([HAVE_DOXYGEN],
 [test -n "$DOXYGEN"])AM_COND_IF([HAVE_DOXYGEN], [AC_CONFIG_FILES([docs/doxyfile])])
 
 
+#enable support for NFQUEUE
+NFQ_ENABLE="no"
+    #NFQ="no"
+    AC_ARG_ENABLE(nfqueue,
+           AS_HELP_STRING([--enable-nfqueue], [Enable NFQUEUE support for Protection Engine]),,[enable_nfqueue=no])
+    AS_IF([test "x$enable_nfqueue" = "xyes"], [
+        CFLAGS="$CFLAGS -DNFQ"
+
+#libnfnetlink
+case $host in
+*-*-mingw32*)
+;;
+*)
+    AC_ARG_WITH(libnfnetlink_includes,
+            [  --with-libnfnetlink-includes=DIR  libnfnetlink include directory],
+            [with_libnfnetlink_includes="$withval"],[with_libnfnetlink_includes=no])
+    AC_ARG_WITH(libnfnetlink_libraries,
+            [  --with-libnfnetlink-libraries=DIR    libnfnetlink library directory],
+            [with_libnfnetlink_libraries="$withval"],[with_libnfnetlink_libraries="no"])
+
+    if test "$with_libnfnetlink_includes" != "no"; then
+    CPPFLAGS="${CPPFLAGS} -I${with_libnfnetlink_includes}"
+    fi
+
+    AC_CHECK_HEADER(libnfnetlink/libnfnetlink.h,,[AC_ERROR(libnfnetlink.h not found ...)])
+
+    if test "$with_libnfnetlink_libraries" != "no"; then
+    LDFLAGS="${LDFLAGS}  -L${with_libnfnetlink_libraries}"
+    fi
+
+    NFNL=""
+    AC_CHECK_LIB(nfnetlink, nfnl_fd,, NFNL="no")
+
+    if test "$NFNL" = "no"; then
+    echo
+    echo "   ERROR!  nfnetlink library not found, go get it"
+    echo "   from www.netfilter.org."
+    echo "   we automatically append libnetfilter_queue/ when searching"
+    echo "   for headers etc. when the --with-libnfnetlink-inlcudes directive"
+    echo "   is used"
+    echo
+    exit 
+    fi
+;;
+esac
+
+#libnetfilter_queue
+    AC_ARG_WITH(libnetfilter_queue_includes,
+            [  --with-libnetfilter_queue-includes=DIR  libnetfilter_queue include directory],
+            [with_libnetfilter_queue_includes="$withval"],[with_libnetfilter_queue_includes=no])
+    AC_ARG_WITH(libnetfilter_queue_libraries,
+            [  --with-libnetfilter_queue-libraries=DIR    libnetfilter_queue library directory],
+            [with_libnetfilter_queue_libraries="$withval"],[with_libnetfilter_queue_libraries="no"])
+
+    if test "$with_libnetfilter_queue_includes" != "no"; then
+    CPPFLAGS="${CPPFLAGS} -I${with_libnetfilter_queue_includes}"
+    fi
+
+    AC_CHECK_HEADER(libnetfilter_queue/libnetfilter_queue.h,,[AC_ERROR(libnetfilter_queue/libnetfilter_queue.h not found ...)])
+
+    if test "$with_libnetfilter_queue_libraries" != "no"; then
+    LDFLAGS="${LDFLAGS}  -L${with_libnetfilter_queue_libraries}"
+    fi
+
+#LDFLAGS="${LDFLAGS} -lnetfilter_queue"
+
+#    NFQ=""
+
+case $host in
+*-*-mingw32*)
+    AC_CHECK_LIB(netfilter_queue, nfq_open,, NFQ="no",-lws2_32)
+
+    AC_ARG_WITH(netfilterforwin_includes,
+            [  --with-netfilterforwin-includes=DIR  netfilterforwin include directory],
+            [with_netfilterforwin_includes="$withval"],[with_netfilterforwin_includes=no])
+
+    if test "$with_netfilterforwin_includes" != "no"; then
+    CPPFLAGS="${CPPFLAGS} -I${with_netfilterforwin_includes}"
+    else
+    CPPFLAGS="${CPPFLAGS} -I../../netfilterforwin"
+    fi
+;;
+*)
+    AC_CHECK_LIB(netfilter_queue, nfq_open,, NFQ="no",)
+    AC_CHECK_LIB([netfilter_queue], [nfq_set_queue_maxlen],AC_DEFINE_UNQUOTED([HAVE_NFQ_MAXLEN],[1],[Found queue max length support in netfilter_queue]) ,,[-lnfnetlink])
+    AC_CHECK_LIB([netfilter_queue], [nfq_set_verdict2],AC_DEFINE_UNQUOTED([HAVE_NFQ_SET_VERDICT2],[1],[Found nfq_set_verdict2 function in netfilter_queue]) ,,[-lnfnetlink])
+
+    # check if the argument to nfq_get_payload is signed or unsigned
+    AC_MSG_CHECKING([for signed nfq_get_payload payload argument])
+    STORECFLAGS="${CFLAGS}"
+    CFLAGS="${CFLAGS} -Werror"
+    AC_COMPILE_IFELSE(
+            [AC_LANG_PROGRAM(
+                [
+                #include <libnetfilter_queue/libnetfilter_queue.h>
+                ],
+                [
+                char *pktdata;
+                nfq_get_payload(NULL, &pktdata);
+                ])],
+            [libnetfilter_queue_nfq_get_payload_signed="yes"],
+            [libnetfilter_queue_nfq_get_payload_signed="no"])
+    AC_MSG_RESULT($libnetfilter_queue_nfq_get_payload_signed)
+    if test "x$libnetfilter_queue_nfq_get_payload_signed" = "xyes"; then
+        AC_DEFINE([NFQ_GET_PAYLOAD_SIGNED], [], [For signed version of nfq_get_payload])
+    fi
+    CFLAGS="${STORECFLAGS}"
+;;
+esac
+
+    if test "$NFQ" = "no"; then
+    echo
+    echo "   ERROR!  libnetfilter_queue library not found, go get it"
+    echo "   from www.netfilter.org."
+    echo "   we automatically append libnetfilter_queue/ when searching"
+    echo "   for headers etc. when the --with-libnfq-includes directive"
+    echo "   is used"
+    echo
+    exit 1 
+	else
+		NFQ_ENABLE="yes"
+    fi
+])
+
 AC_OUTPUT([
 Makefile
 asm/Makefile
@@ -64,6 +188,7 @@ src/opcodes/Makefile
 src/bus/Makefile
 src/core/Makefile
 src/detection/Makefile
+src/protection/Makefile
 pdf/Makefile
 test/Makefile
 test/pcapfiles/Makefile
@@ -81,5 +206,6 @@ echo "
   C Compiler...........: $CXX $CXXFLAGS $CPPFLAGS
   Linker...............: $LD $LDFLAGS $LIBS
   Doxygen..............: $enable_doxygen
+  Protection Engine....: $NFQ_ENABLE
 "
 
